function A_sym = compute_A(in1,u,mL,R,mb,h,mw,Ib,Iw,Irod,g,Fr)
%compute_A
%    A_sym = compute_A(IN1,U,mL,R,MB,H,MW,Ib,Iw,Irod,G,Fr)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    28-Jun-2026 19:10:10

z1 = in1(1,:);
z2 = in1(2,:);
z3 = in1(3,:);
z4 = in1(4,:);
t2 = cos(z1);
t3 = sin(z1);
t4 = R.^2;
t5 = h.^2;
t6 = mL.^2;
t7 = z2.^2;
t8 = z2.^3;
t9 = z3.^2;
t10 = 1.0./mL;
t13 = R.*h.*mb.*2.0;
t11 = mb.*t4;
t12 = mw.*t4;
t14 = mb.*t5;
t15 = mL.*t7.*2.0;
t16 = Ib+Irod+Iw+t11+t12+t13+t14+t15;
t17 = 1.0./t16;
t18 = t17.^2;
et1 = t18.*z2.*(-Fr.*t11-Fr.*t12-Fr.*t14+Ib.*u+Irod.*u+Iw.*u+t11.*u+t12.*u+t13.*u+t14.*u+t15.*u-Fr.*Ib-Fr.*Irod-Fr.*Iw-Fr.*mL.*t4.*2.0-Fr.*mL.*t7.*2.0+mL.*t4.*u.*2.0+t6.*t8.*t9.*4.0+Ib.*mL.*t9.*z2.*2.0+Irod.*mL.*t9.*z2.*2.0+Iw.*mL.*t9.*z2.*2.0+g.*mL.*t3.*t13+g.*mL.*t3.*t14.*2.0+g.*t3.*t6.*t7.*4.0+mL.*t9.*t11.*z2.*2.0+mL.*t9.*t12.*z2.*2.0+mL.*t9.*t14.*z2.*2.0+t4.*t6.*t9.*z2.*4.0-Fr.*R.*h.*mb.*2.0+Ib.*g.*mL.*t3.*2.0+Irod.*g.*mL.*t3.*2.0+Iw.*g.*mL.*t3.*2.0-R.*g.*t2.*t6.*z2.*4.0+R.*t6.*z2.*z3.*z4.*8.0+R.*h.*mL.*mb.*t9.*z2.*4.0).*-2.0;
et2 = (t10.*t17.*(Ib.*mL.*t9.*2.0+Irod.*mL.*t9.*2.0+Iw.*mL.*t9.*2.0-Fr.*mL.*z2.*4.0+mL.*t9.*t11.*2.0+mL.*t9.*t12.*2.0+mL.*t9.*t14.*2.0+t4.*t6.*t9.*4.0+t6.*t7.*t9.*1.2e+1+mL.*u.*z2.*4.0-R.*g.*t2.*t6.*4.0+R.*t6.*z3.*z4.*8.0+g.*t3.*t6.*z2.*8.0+R.*h.*mL.*mb.*t9.*4.0))./2.0;
mt1 = [0.0,0.0,t17.*(g.*h.*mb.*t2-g.*mL.*t3.*z2.*2.0+R.*g.*mb.*t2+R.*g.*mw.*t2),(t10.*t17.*(g.*mL.*t2.*t13+g.*mL.*t2.*t14.*2.0+g.*t2.*t6.*t7.*4.0+Ib.*g.*mL.*t2.*2.0+Irod.*g.*mL.*t2.*2.0+Iw.*g.*mL.*t2.*2.0+R.*g.*t3.*t6.*z2.*4.0))./2.0,0.0,0.0,-t17.*(R.*mL.*t9.*2.0-g.*mL.*t2.*2.0+mL.*z3.*z4.*4.0)-mL.*t18.*z2.*(-R.*u+Fr.*R-R.*mL.*t9.*z2.*2.0+g.*h.*mb.*t3+g.*mL.*t2.*z2.*2.0-mL.*z2.*z3.*z4.*4.0+R.*g.*mb.*t3+R.*g.*mw.*t3).*4.0,et1+et2,1.0,0.0,-t17.*(mL.*z2.*z4.*4.0+R.*mL.*z2.*z3.*4.0)];
mt2 = [(t10.*t17.*(t6.*t8.*z3.*8.0+Ib.*mL.*z2.*z3.*4.0+Irod.*mL.*z2.*z3.*4.0+Iw.*mL.*z2.*z3.*4.0+R.*t6.*z2.*z4.*8.0+mL.*t11.*z2.*z3.*4.0+mL.*t12.*z2.*z3.*4.0+mL.*t14.*z2.*z3.*4.0+t4.*t6.*z2.*z3.*8.0+R.*h.*mL.*mb.*z2.*z3.*8.0))./2.0,0.0,1.0,mL.*t17.*z2.*z3.*-4.0,R.*mL.*t17.*z2.*z3.*4.0];
A_sym = reshape([mt1,mt2],4,4);
end
