function B_sym = compute_B(in1,mL,R,mb,h,mw,Ib,Iw,Irod)
%compute_B
%    B_sym = compute_B(IN1,mL,R,MB,H,MW,Ib,Iw,Irod)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    28-Jun-2026 19:10:10

z2 = in1(2,:);
t2 = R.^2;
t3 = h.^2;
t4 = z2.^2;
t7 = R.*h.*mb.*2.0;
t5 = mb.*t2;
t6 = mw.*t2;
t8 = mb.*t3;
t9 = mL.*t4.*2.0;
t10 = Ib+Irod+Iw+t5+t6+t7+t8+t9;
t11 = 1.0./t10;
B_sym = [0.0;0.0;-R.*t11;(t11.*(t10+mL.*t2.*2.0))./(mL.*2.0)];
end
